/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as MateriRouteImport } from './routes/materi'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as TugasRouteImport } from './routes/tugas'
import { Route as UjianRouteImport } from './routes/ujian'
import { Route as BelajarIndexRouteImport } from './routes/belajar.index'
import { Route as BelajarIdRouteImport } from './routes/belajar.$id'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriRoute = MateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const TugasRoute = TugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => rootRouteImport,
} as any)
const UjianRoute = UjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarIndexRoute = BelajarIndexRouteImport.update({
  id: '/belajar/',
  path: '/belajar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarIdRoute = BelajarIdRouteImport.update({
  id: '/belajar/$id',
  path: '/belajar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jadwal': typeof JadwalRoute
  '/materi': typeof MateriRoute
  '/timer': typeof TimerRoute
  '/tugas': typeof TugasRoute
  '/ujian': typeof UjianRoute
  '/belajar/$id': typeof BelajarIdRoute
  '/belajar/': typeof BelajarIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jadwal': typeof JadwalRoute
  '/materi': typeof MateriRoute
  '/timer': typeof TimerRoute
  '/tugas': typeof TugasRoute
  '/ujian': typeof UjianRoute
  '/belajar/$id': typeof BelajarIdRoute
  '/belajar': typeof BelajarIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jadwal': typeof JadwalRoute
  '/materi': typeof MateriRoute
  '/timer': typeof TimerRoute
  '/tugas': typeof TugasRoute
  '/ujian': typeof UjianRoute
  '/belajar/$id': typeof BelajarIdRoute
  '/belajar/': typeof BelajarIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jadwal'
    | '/materi'
    | '/timer'
    | '/tugas'
    | '/ujian'
    | '/belajar/$id'
    | '/belajar/'
    | '/api/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jadwal'
    | '/materi'
    | '/timer'
    | '/tugas'
    | '/ujian'
    | '/belajar/$id'
    | '/belajar'
    | '/api/google/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/jadwal'
    | '/materi'
    | '/timer'
    | '/tugas'
    | '/ujian'
    | '/belajar/$id'
    | '/belajar/'
    | '/api/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JadwalRoute: typeof JadwalRoute
  MateriRoute: typeof MateriRoute
  TimerRoute: typeof TimerRoute
  TugasRoute: typeof TugasRoute
  UjianRoute: typeof UjianRoute
  BelajarIdRoute: typeof BelajarIdRoute
  BelajarIndexRoute: typeof BelajarIndexRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materi': {
      id: '/materi'
      path: '/materi'
      fullPath: '/materi'
      preLoaderRoute: typeof MateriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tugas': {
      id: '/tugas'
      path: '/tugas'
      fullPath: '/tugas'
      preLoaderRoute: typeof TugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujian': {
      id: '/ujian'
      path: '/ujian'
      fullPath: '/ujian'
      preLoaderRoute: typeof UjianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/': {
      id: '/belajar/'
      path: '/belajar'
      fullPath: '/belajar/'
      preLoaderRoute: typeof BelajarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/$id': {
      id: '/belajar/$id'
      path: '/belajar/$id'
      fullPath: '/belajar/$id'
      preLoaderRoute: typeof BelajarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JadwalRoute: JadwalRoute,
  MateriRoute: MateriRoute,
  TimerRoute: TimerRoute,
  TugasRoute: TugasRoute,
  UjianRoute: UjianRoute,
  BelajarIdRoute: BelajarIdRoute,
  BelajarIndexRoute: BelajarIndexRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
